import Head from "next/head";
import React, { useEffect, useState, useContext } from "react";
import UserContext from "./context/UserContext";
import { useRouter } from "next/router";

import styles from "../styles/Home.module.css";
import Addmessage from "./component/addmessage";
import Messages from "./component/Messages";

export default function Home(props) {
  const router = useRouter();

  const context = useContext(UserContext);
  const { user, getuser } = context;

  useEffect(() => {
    if (localStorage.getItem("token")) {
      getuser();
    } else {
      router.push("/Signin");
    }
    // eslint-disable-next-line
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>MERN </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="flex flex-col items-center justify-center  space-y-7 ">
          <h1 className="text-3xl font-bold  my-4   ">
            Welcome to the Mern Project{" "}
            <span className="text-4xl text-purple-500 mx-5"> {user.name}</span>
          </h1>
          <Addmessage />
        </div>
        <Messages />
      </main>
    </div>
  );
}
